meta_product_name: ApprentiClic

meta_title: ApprentiClic – Cours d'informatique en ligne

meta_description: Cours d'informatique de base en ligne pour l'autonomie de tous sur Internet

meta_image: cover.png # should exist in `app/assets/images/`
